version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ${HOME}/.ssh:/root/.ssh:ro
    command: sh -c "npm ci && npx prisma generate && npm run dev"
    depends_on:
      db:
        condition: service_healthy   # ← 待機
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app?schema=public
      - NODE_ENV=development
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/readyz >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 6
      start_period: 10s
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"         # ローカルから接続したい場合のみ
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  db_data:
