version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - /app/node_modules
      - ${HOME}/.ssh:/root/.ssh:ro
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy   # ← 待機
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app?schema=public
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"         # ローカルから接続したい場合のみ
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  db_data:
