name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Docker Compose は ubuntu-latest で標準利用可
      - name: Pull images (optional)
        run: docker compose -f docker-compose.yml pull || true

      - name: Start DB only
        run: docker compose -f docker-compose.yml up -d db

      - name: Wait for Postgres healthy
        run: |
          for i in {1..60}; do
            if docker compose exec -T db pg_isready -U postgres -d app; then
              echo "DB is ready"; exit 0
            fi
            echo "Waiting for DB... ($i)"
            sleep 2
          done
          echo "DB did not become ready in time"; exit 1

      # CI 用オーバーライドで app はテストコマンドに差し替え
      - name: Run tests in app container
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml up \
            --abort-on-container-exit --exit-code-from app

      - name: Show app logs on failure
        if: failure()
        run: docker compose logs --no-color app || true

      - name: Teardown
        if: always()
        run: docker compose down -v